from typing import List, Optional
from sqlalchemy.orm import Session
from .auth import hash_password, verify_password, create_access_token
from .models import User

from . import models, schemas


# -------- City --------
def get_cities(db: Session) -> List[models.City]:
    return db.query(models.City).order_by(models.City.name).all()


def get_city(db: Session, city_id: int) -> Optional[models.City]:
    return db.query(models.City).filter(models.City.id == city_id).first()


def get_city_by_name(db: Session, name: str) -> Optional[models.City]:
    return db.query(models.City).filter(models.City.name == name).first()


def create_city(db: Session, city: schemas.CityCreate) -> models.City:
    db_city = models.City(name=city.name, country=city.country)
    db.add(db_city)
    db.commit()
    db.refresh(db_city)
    return db_city


# -------- Itinerary --------
def create_itinerary(db: Session, itinerary_in: schemas.ItineraryCreate) -> models.Itinerary:
    # basic "AI-like" autogenerated notes if not provided
    notes = itinerary_in.notes or (
        f"Personalized {itinerary_in.days}-day itinerary for {itinerary_in.traveler_name} "
        f"in city ID {itinerary_in.city_id}, optimized for budget ~{itinerary_in.budget}."
    )

    itinerary = models.Itinerary(
        traveler_name=itinerary_in.traveler_name,
        traveler_email=itinerary_in.traveler_email,
        city_id=itinerary_in.city_id,
        days=itinerary_in.days,
        budget=itinerary_in.budget,
        notes=notes,
    )
    db.add(itinerary)
    db.flush()  # so we get itinerary.id before commit

    # Day plans: either take from client or auto-generate simple ones
    if itinerary_in.day_plans:
        for d in itinerary_in.day_plans:
            day = models.ItineraryDay(
                itinerary_id=itinerary.id,
                day_number=d.day_number,
                morning=d.morning,
                afternoon=d.afternoon,
                evening=d.evening,
            )
            db.add(day)
    else:
        for day_number in range(1, itinerary_in.days + 1):
            db.add(
                models.ItineraryDay(
                    itinerary_id=itinerary.id,
                    day_number=day_number,
                    morning=f"Explore iconic landmarks of the city (Day {day_number}).",
                    afternoon="Local food tour and cultural spots.",
                    evening="Sunset viewpoint and relaxing dinner.",
                )
            )

    db.commit()
    db.refresh(itinerary)
    return itinerary


def get_itinerary(db: Session, itinerary_id: int) -> Optional[models.Itinerary]:
    return (
        db.query(models.Itinerary)
        .filter(models.Itinerary.id == itinerary_id)
        .first()
    )


def list_itineraries(db: Session, traveler_email: Optional[str] = None) -> List[models.Itinerary]:
    query = db.query(models.Itinerary)
    if traveler_email:
        query = query.filter(models.Itinerary.traveler_email == traveler_email)
    return query.order_by(models.Itinerary.id.desc()).all()


#----------------create user-------------------------

def create_user(db: Session, user: schemas.UserCreate):
    hashed = hash_password(user.password)

    db_user = User(name=user.name, email=user.email, password=hashed)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user


#----------------authentivate-----------------

def authenticate_user(db: Session, email: str, password: str):
    user = db.query(User).filter(User.email == email).first()
    if not user or not verify_password(password, user.password):
        return None
    return user

#===================login_user--------------------

def login_user(db: Session, email: str, password: str):
    user = authenticate_user(db, email, password)
    if not user:
        return None
    
    token = create_access_token({"sub": str(user.id)})
    return token

